extends:
    - airbnb-typescript/base
    - plugin:jest/recommended
    - prettier
    - plugin:@typescript-eslint/recommended
    - prettier/@typescript-eslint
    - plugin:prettier/recommended

plugins:
    - node
    - jest
    - prettier
    - '@typescript-eslint'

parser: '@typescript-eslint/parser'

parserOptions:
    ecmaVersion: 2018
    sourceType: module
    project: ["./tsconfig.json"]

rules:
    '@typescript-eslint/no-explicit-any': off
    '@typescript-eslint/dot-notation': off
    import/no-cycle: off
    no-console: off
    no-else-return: off
    node/exports-style:
        - error
        - module.exports
    no-await-in-loop: off
    no-restricted-syntax: off
    no-underscore-dangle: off
    prefer-destructuring: off
    no-plusplus: off
    valid-jsdoc: off
    no-loop-func: off
    no-param-reassign: off
    no-return-assign:
        - error
        - except-parens
    prettier/prettier:
        - warn
        -
            printWidth: 100
            tabWidth: 4
            singleQuote: true

env:
    jest: true
    es6: true
    node: true
